---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: brandwatch-react-app
  - name: dependency-cache

outputs:
  - name: build

run:
  path: brandwatch-react-app/ci/scripts/run_build.sh
