---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: source
  - name: node-modules

outputs:
  - name: build

run:
  path: source/ci/scripts/run_build.sh
