resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest
      yarn-support: true
  - name: google-cloud-storage
    type: docker-image
    source:
      repository: frodenas/gcs-resource
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: source
    type: git
    source: &repo-source
      uri: https://github.com/thatguynamedandy/brandwatch-react-app
      check_every: 5s
      branch: gcp-integration
  - name: node-modules
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json
  - name: release-artifact
    type: google-cloud-storage
    source:
      bucket: 5e04f35d
      regexp: releases/brandwatch-react-app.(.*).tar.gz"
      json_key: ((gcs-prod-token))
  - name: slack
    type: slack-notification
    source:
      url: ((slack-hook))

jobs:
  - name: install-dependencies
    plan:
      - get: source
        trigger: true
      - get: node-modules
  - name: run-tests
    plan:
      - get: source
        trigger: true
        passed: [install-dependencies]
      - get: node-modules
        passed: [install-dependencies]
      - aggregate:
        - task: run lint rules
          file: source/ci/tasks/run_lint.yml
        - task: run unit tests
          file: source/ci/tasks/run_tests.yml
  - name: run-build
    plan:
      - get: node-modules
        passed: [run-tests]
      - get: source
        trigger: true
        passed: [run-tests]
      - task: run build
        file: source/ci/tasks/run_build.yml
      - put: release-artifact
        params: { file: ./build/brandwatch-react-app.*.tar.gz }
  - name: deploy-stage
    plan:
      - get: release-artifact
        trigger: true
        passed: [run-build]
      - get: source
        trigger: true
        passed: [run-build]
      - task: deploy to stage
        file: source/ci/tasks/run_deploy.yml
        params: {
          GCP_SERVICE_ACCOUNT_KEY: ((gcs-stage-token)),
          STORAGE_BUCKET: my-platform-stage-gcp0-bwcom-net
        }
  - name: run-stage-automation
    plan:
      - get: source
        trigger: true
        passed: [deploy-stage]
      - task: run automation on stage
        file: source/ci/tasks/run_automation.yml
        params: {
          STORAGE_BUCKET: my-platform-stage-gcp0-bwcom-net
        }
  - name: deploy-live
    plan:
      - get: release-artifact
        trigger: true
        passed: [run-build]
      - get: source
        trigger: true
        passed: [run-stage-automation]
      - task: deploy to live
        file: source/ci/tasks/run_deploy.yml
        params: {
          GCP_SERVICE_ACCOUNT_KEY: ((gcs-prod-token)),
          STORAGE_BUCKET: my-platform-prod-gcp0-bwcom-net
        }
  - name: run-live-automation
    plan:
      - get: source
        trigger: true
        passed: [deploy-live]
      - task: run automation on live
        file: source/ci/tasks/run_automation.yml
        params: {
          STORAGE_BUCKET: my-platform-stage-gcp0-bwcom-net
        }
      - put: slack
        params:
          text: "Success"
